# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: Swapnil's Tutoring
tagline: "High Quality Tutoring for High School and College Students"
description: "Tutoring in advanced math, physics, and computer science for high school and college students."
url: https://SwapnilPande.github.io
baseurl: /swapnils-tutoring

author:
  name: "Swapnil Pande"

paginate: 5

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/SwapnilPande/swapnils-tutoring
