# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty
relative_permalinks: true

# Setup
title: Swapnil's Tutoring
tagline: "High Quality Tutoring for High School and College Students"
description: "Swapnil is a great tutor."
url: http://hyde.getpoole.com
baseurl: /

author:
  name: "Swapnil Pande"
  url: https://linkedin.com/in/SwapnilPande

paginate: 5

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/SwapnilPande/swapnils-tutoring
